"""Deterministic estimators for the conserved manifold-regime study.

The public API exposes both transparent functional estimators and lightweight
scikit-learn-compatible estimator classes.  All temporal estimators accept
``segment_ids`` so that discontinuous epochs are never joined accidentally.
"""

from .alignment import (
    AlignmentSummary,
    CommunicationSubspaceModel,
    PairwiseAlignmentSummary,
    communication_subspace_alignment,
    fit_communication_subspace,
    lagged_shared_predictive_variance,
    pairwise_module_alignment,
    principal_angles,
)
from .directionality import (
    DirectionalityEstimator,
    DirectionalitySummary,
    entropy_production,
    estimate_directionality,
    estimate_stationary_distribution,
    estimate_transition_matrix,
)
from .matching import (
    MatchedMetricResult,
    matched_sample_indices,
    sample_matched_metric,
    segment_ids_from_indices,
)
from .metastability import (
    MetastabilityEstimator,
    MetastabilityReference,
    MetastabilitySummary,
    estimate_metastability,
    metastability_score,
    persistence_revisability_profile,
)
from .profile import (
    FiveAxisProfileEstimator,
    ManifoldProfile,
    ManifoldProfileDetails,
    ManifoldProfileEstimator,
    ManifoldRecord,
)
from .reachability import (
    LocalLinearDynamics,
    ReachabilityEstimator,
    ReachabilitySummary,
    StateWeightedReachabilitySummary,
    fit_local_linear_dynamics,
    reachability_energy,
    state_weighted_reachability,
    stochastic_gramian_logdet,
    stochastic_reachability_gramian,
    summarize_reachability,
)
from .repertoire import (
    RepertoireEstimator,
    RepertoireSummary,
    covariance_participation_ratio,
    covariance_spectrum,
    estimate_repertoire,
    knn_differential_entropy,
    knn_entropy,
    knn_intrinsic_dimension,
    local_anisotropy,
    local_neighbourhood_anisotropy,
    participation_ratio,
)
from .surrogates import (
    block_permutation,
    covariance_matched_surrogate,
    dwell_matched_state_surrogate,
    iaaft_surrogate,
    permute_channels,
    phase_randomized_surrogate,
    rotate_channels,
    state_space_surrogate,
)

__all__ = [
    "AlignmentSummary",
    "CommunicationSubspaceModel",
    "DirectionalityEstimator",
    "DirectionalitySummary",
    "FiveAxisProfileEstimator",
    "LocalLinearDynamics",
    "ManifoldProfile",
    "ManifoldProfileDetails",
    "ManifoldProfileEstimator",
    "ManifoldRecord",
    "MatchedMetricResult",
    "MetastabilityEstimator",
    "MetastabilityReference",
    "MetastabilitySummary",
    "PairwiseAlignmentSummary",
    "ReachabilityEstimator",
    "ReachabilitySummary",
    "RepertoireEstimator",
    "RepertoireSummary",
    "StateWeightedReachabilitySummary",
    "block_permutation",
    "communication_subspace_alignment",
    "covariance_matched_surrogate",
    "covariance_participation_ratio",
    "covariance_spectrum",
    "dwell_matched_state_surrogate",
    "entropy_production",
    "estimate_directionality",
    "estimate_metastability",
    "estimate_repertoire",
    "estimate_stationary_distribution",
    "estimate_transition_matrix",
    "fit_communication_subspace",
    "fit_local_linear_dynamics",
    "iaaft_surrogate",
    "knn_differential_entropy",
    "knn_entropy",
    "knn_intrinsic_dimension",
    "lagged_shared_predictive_variance",
    "local_anisotropy",
    "local_neighbourhood_anisotropy",
    "matched_sample_indices",
    "metastability_score",
    "pairwise_module_alignment",
    "participation_ratio",
    "permute_channels",
    "persistence_revisability_profile",
    "phase_randomized_surrogate",
    "principal_angles",
    "reachability_energy",
    "rotate_channels",
    "sample_matched_metric",
    "segment_ids_from_indices",
    "state_space_surrogate",
    "state_weighted_reachability",
    "stochastic_gramian_logdet",
    "stochastic_reachability_gramian",
    "summarize_reachability",
]
